#!/usr/bin/env bash
if [[ ! -d ~/.clv/home/node ]]; then
    echo "clv is initializing node"
    mkdir -p ~/.clv/home/node
    docker run --rm \
        -v "$HOME/.clv/home:/root" \
        -v "$PWD:/clv" \
        -w "/clv" \
        node npm config set prefix "/root/node"
fi

if [[ $1 ]]; then
  if [[ ! -e ~/.clv/home/node/bin/$1 ]]; then
    echo "clv is initializing $1"
    if [[ $2 ]]; then
      npm i -g "$2"
    else
      npm i -g "$1"
    fi
  fi
fi