#!/usr/bin/env bash
if [[ -t 0 ]]; then TTY="yes"; fi

if [[ "$TTY" == "yes" ]]; then
    SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

    # --- uninstall clv commands if any --- #
    "$SCRIPT_PATH"/uninstall bin

    # --- prepare clv's home directory --- #
    mkdir -p ~/.clv
    if [[ -e ~/.clv.home.bak ]]; then
        echo "restoring clv's home directory"
        mv ~/.clv.home.bak ~/.clv/home
    fi

    # --- installing clv --- #
    sudo cp -r "$SCRIPT_PATH"/inc /usr/local/bin/
    sudo cp -r "$SCRIPT_PATH"/init /usr/local/bin/
    for CMD_PATH in "$SCRIPT_PATH"/bin/*; do
        CMD=$(basename "$CMD_PATH")
        if [[ ! -e "/usr/local/bin/$CMD" ]]; then
            sudo cp "$SCRIPT_PATH/bin/$CMD" "/usr/local/bin/$CMD"
            echo "clv installed $CMD successfully!"
        fi
    done
else
    wget https://github.com/Clouve/clv/archive/master.zip
    unzip master.zip
    ./clv-master/install
    rm -rf clv-master master.zip
fi

echo "clv has been installed successfully!"
