#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# --- uninstall existing clv if any --- #
if [[ -e ~/.bash_profile ]] && grep -q "#ADDED BY CLV INSTALLER#" ~/.bash_profile; then
    ./uninstall
fi

# --- install clv --- #
mkdir ~/.clv
mkdir ~/.clv/bin
touch ~/.bash_profile
export PATH="~/.clv/bin:$PATH"
echo "export PATH=\"~/.clv/bin:\$PATH\" #ADDED BY CLV INSTALLER#" > ~/.bash_profile
for cmd in "$SCRIPTPATH"/bin/*
do
    "$cmd" clv-install
done

echo "clv has been installed successfully!"