#!/usr/bin/env bash
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# --- uninstall clv commands if any --- #
"$SCRIPT_PATH"/uninstall bin

# --- install clv --- #
mkdir -p ~/.clv
if [[ -e ~/.clv.home.bak ]]; then
    echo "restoring clv's home directory"
    mv ~/.clv.home.bak ~/.clv/home
fi
for cmd in "$SCRIPT_PATH"/bin/*; do
    "$cmd" clv-install
done

echo "clv has been installed successfully!"