#!/usr/bin/env bash
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

uninstall_commands(){
    for CMD_PATH in $@; do
        CMD=$(basename "$CMD_PATH")
        if [[ -e "/usr/local/bin/$CMD" ]]; then
          if [[ ! -d "/usr/local/bin/$CMD" ]]; then
            sudo rm "/usr/local/bin/$CMD"
            echo "clv uninstalled $CMD successfully!"
          fi
        fi
    done
}

if [[ $1 ]]; then
    uninstall_commands $@
else
    uninstall_commands "$SCRIPT_PATH"/bin/*
    if [[ -d /usr/local/bin/inc ]]; then
        sudo rm -rf /usr/local/bin/inc
    fi
    if [[ -d /usr/local/bin/init ]]; then
        sudo rm -rf /usr/local/bin/init
    fi
    if [[ -e "$HOME/.clv/.init" ]]; then
        sudo rm "$HOME/.clv/.init"
    fi
    echo "clv has been uninstalled successfully!"
fi
echo "----------------------------------------------------------"
